---
- name: Uninstall K3s from all nodes
  hosts: servers:agents
  gather_facts: false
  become: true

  tasks:
  - name: Run K3s uninstall script [server]
    when: "'servers' in group_names"
    ansible.builtin.command:
      cmd: k3s-uninstall.sh
      removes: /var/lib/rancher/k3s/*

  - name: Run K3s uninstall script [agent]
    when: "'agents' in group_names"
    ansible.builtin.command:
      cmd: k3s-agent-uninstall.sh
      removes: /var/lib/rancher/k3s/*
