---
- name: Test K3s token sharing
  hosts: k3s_cluster
  gather_facts: false

  tasks:
  - name: Read K3s token file from first server
    become: true
    when: "inventory_hostname == groups['servers'][0]"
    ansible.builtin.slurp:
      src: /var/lib/rancher/k3s/server/token
    register: token_file

  - name: Set token fact on first server
    when: "inventory_hostname == groups['servers'][0]"
    ansible.builtin.set_fact:
      token: "{{ token_file['content'] | b64decode | trim }}"

  - name: Set token fact on rest of servers and agents
    when: "inventory_hostname != groups['servers'][0]"
    ansible.builtin.set_fact:
      token: "{{ hostvars[groups['servers'][0]]['token'] }}"

  - name: All servers and agents show the token
    ansible.builtin.debug:
      msg: "Token = {{ token | default('undefined') }}"
