---
- name: Test inventory and variables
  hosts: all
  connection: local
  gather_facts: no

  tasks:
  - name: Show current host
    debug:
      msg: "Host is {{ inventory_hostname }}"

  - name: Show k3s version
    debug:
      msg: "k3s_version = {{ k3s_version | default('undefined') }}"

  - name: Show API endpoint VIP
    debug:
      msg: "api_endpoint_vip = {{ api_endpoint_vip | default('undefined') }}"

  - name: First server only
    when: "inventory_hostname == groups['servers'][0]"
    debug:
      msg: "Server = {{ inventory_hostname }}"

  - name: Rest of servers
    when: "inventory_hostname != groups['servers'][0] and 'servers' in group_names"
    debug:
      msg: "Server = {{ inventory_hostname }}"

  - name: All agents
    when: "'agents' in group_names"
    debug:
      msg: "Server = {{ inventory_hostname }}"
